SELECT 
    SAFE_CAST(REGEXP_REPLACE( LTRIM(CL ,'0'), r'\.0$', '') AS STRING) id_logradouro,
    SAFE_CAST(Nome AS STRING) nome,
    SAFE_CAST(NOME_PARCIAL AS STRING) nome_parcial,
    SAFE_CAST(COMPLETO AS STRING) nome_completo,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(COD_TRECHO ,'0'), r'\.0$', '') AS STRING) id_trecho,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(COD_SIT_TRECHO ,'0'), r'\.0$', '') AS STRING) id_situacao_trecho,
    SAFE_CAST(SIT_TRECHO AS STRING) situacao_trecho,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(COD_TIPO_LOGRA ,'0'), r'\.0$', '') AS STRING) id_tipo,
    SAFE_CAST(TIPO_LOGRA_EXT AS STRING) tipo,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(Cod_Bairro ,'0'), r'\.0$', '') AS STRING) id_bairro,
    SAFE_CAST(NP_INI_PAR AS INT64) inicio_numero_porta_par,
    SAFE_CAST(NP_FIN_PAR AS INT64) final_numero_porta_par,
    SAFE_CAST(NP_INI_IMP AS INT64) inicio_numero_porta_impar,
    SAFE_CAST(NP_FIN_IMP AS INT64) final_numero_porta_impar,
    SAFE_CAST(HIERARQUIA AS STRING) hierarquia,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(CHAVEGEO_TR ,'0'), r'\.0$', '') AS STRING) id_chavegeo,
    ST_GEOGFROMTEXT(geometry) AS geometry,
FROM `rj-escritorio-dev.dados_mestres_staging.logradouro` 