SELECT 
    SAFE_CAST(REGEXP_REPLACE( LTRIM(cl ,'0'), r'\.0$', '') AS STRING) id_logradouro,
    SAFE_CAST(nome AS STRING) nome,
    SAFE_CAST(nome_parci AS STRING) nome_parcial,
    SAFE_CAST(completo AS STRING) nome_completo,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_trecho ,'0'), r'\.0$', '') AS STRING) id_trecho,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_sit_tr ,'0'), r'\.0$', '') AS STRING) id_situacao_trecho,
    SAFE_CAST(sit_trecho AS STRING) situacao_trecho,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_tipo_l ,'0'), r'\.0$', '') AS STRING) id_tipo,
    SAFE_CAST(tipo_log_1 AS STRING) tipo,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_bairro ,'0'), r'\.0$', '') AS STRING) id_bairro,
    SAFE_CAST(np_ini_par AS INT64) inicio_numero_porta_par,
    SAFE_CAST(np_fin_par AS INT64) final_numero_porta_par,
    SAFE_CAST(np_ini_imp AS INT64) inicio_numero_porta_impar,
    SAFE_CAST(np_fin_imp AS INT64) final_numero_porta_impar,
    SAFE_CAST(hierarquia AS STRING) hierarquia,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(chavegeo_t ,'0'), r'\.0$', '') AS STRING) id_chavegeo,
    ST_GEOGFROMTEXT(geometry) AS geometry,
FROM `rj-escritorio-dev.dados_mestres_staging.logradouro` 