SELECT 
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_np ,'0') , r'\.0$', '') AS STRING) id_numero_porta,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_trecho ,'0') , r'\.0$', '') AS STRING) id_trecho,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cl ,'0') , r'\.0$', '') AS STRING) id_logradouro,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cl_original ,'0') , r'\.0$', '') AS STRING) id_logradouro_original,
    SAFE_CAST(TRIM(clnp_ass) AS STRING) AS id_logradouro_numero_porta_associado,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_quadra ,'0') , r'\.0$', '') AS STRING) id_quadra,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_face ,'0') , r'\.0$', '') AS STRING) id_face,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(cod_lote ,'0') , r'\.0$', '') AS STRING) id_lote,
    SAFE_CAST(REGEXP_REPLACE(cep , r'\.0$', '') AS STRING) cep,
    SAFE_CAST(TRIM(np) AS INT64) AS numero_porta,
    SAFE_CAST(TRIM(np_int) AS INT64) AS numero_porta_short,
    SAFE_CAST(TRIM(compl_np) AS STRING) AS complemento_numero_porta,
    SAFE_CAST(TRIM(num_adj_a) AS STRING) AS numero_adjacente_a,
    SAFE_CAST(TRIM(num_adj_b) AS STRING) AS numero_adjacente_b,
    SAFE_CAST(TRIM(num_pavimentos) AS INT64) AS numero_pavimentos,
    SAFE_CAST(TRIM(dist_lote) AS FLOAT64) AS distancia_lote,
    SAFE_CAST(REGEXP_REPLACE(LTRIM(chavegeo_np ,'0'), r'\.0$', '') AS STRING) id_chavegeo,
    SAFE_CAST(TRIM(x) AS STRING) AS x,
    SAFE_CAST(TRIM(y) AS STRING) AS y,
    geometry_wkt,
    SAFE.ST_GEOGFROMTEXT(geometry) AS geometry,
FROM `rj-escritorio-dev.dados_mestres_staging.numero_porta` AS t