
version: 2

models:
  - name: bairro
    description: | 
      Descrição                : Bairros da Cidade do Rio de Janeiro
      Frequência de atualização: Segundo aprovação / delimitação / implantação
      Cobertura temporal       : Segundo atualização
      Órgão gestor dos dados   : IPP / Câmara dos Vereadores
      Publicado por (Nome)     : IPP
      Publicado por (E-mail)   : contato.siurb@gmail.com
      Banco de origem          : srv000420/BaseGeo
      View ou Tabela de Origem : BaseGeo.DBO.LimiteBairro

    columns:
      - name: id_bairro
        description: Código do bairro dado pela prefeitura do Rio de Janeiro.
      - name: nome
        description: Nome do bairro.
      - name: id_area_planejamento
        description: Código da área de planejamento onde está localizado a região de planejamento do bairro. Ver atributo RP.
      - name: nome_regiao_planejamento
        description: Nome da região de planejamento. Deve respeitar o atributo Cod_RP.
      - name: id_regiao_planejamento
        description: Código da região de planejamento onde está localizado o região administrativa do bairro. Ver atributo REGIAO_ADM.
      - name: id_regiao_administrativa
        description: Código da região administrativa onde está locallizado o bairro.
      - name: nome_regiao_administrativa
        description: Nome da região administrativa onde está localizado o bairro. Este atributo deve respeitar o atributo CODRA.
      - name: area
        description: Área (m²) do bairro. Tem o mesmo valor do atributo SHAPE.STArea().
      - name: perimetro
        description: Perímetro (m) do bairro.
      - name: geometry
        description: Geometria do bairro no banco do ArcGIS.