SELECT
CAST(LEGISLACAO AS string) AS legislacao,
CAST(ZONA AS string) AS zona,
CAST(SUBZONA AS string) AS subzona,
CAST(SIGLA AS string) AS sigla_zona_subzona,
CAST(AP AS string) AS area_planejamento,
CAST(CAB AS string) AS coeficiente_aproveitamento_basico,
CAST(obs_cab AS string) AS legislacao_coeficiente_basico,
CAST(CAM AS string) AS coeficiente_aproveitamento_maximo,
CAST(obs_cam AS string) AS legislacao_coeficiente_maximo,
CAST(to_ AS string) AS taxa_ocupacao,
CAST(obs_to AS string) AS legislacao_taxa_ocupacao,
CAST(LOTE_MIN AS string) AS lote_minimo,
CAST(obs_lote_m AS string) AS legislacao_lote_minimo,
CAST(TESTADA_MI AS string) AS testada_minima,
CAST(obs_testad AS string) AS legislacao_testada_minima,
CAST(GAB_AFAST AS string) AS gabarito_afastado,
CAST(obs_gab_af AS string) AS legislacao_gabarito_afastado,
CAST(GAB_N_AFAS AS string) AS gabarito_nao_afastado,
CAST(obs_gab_n_ AS string) AS legislacao_gabarito_nao_afastado,
CAST(AFAST_FRON AS string) AS afastamento_frontal,
CAST(obs_afast_ AS string) AS legislacao_afastamento_frontal,
CAST(ICS AS string) AS indice_comercio_servico,
CAST(obs_ics AS string) AS calculo_indice_comercio_servico,
CAST(obs_riu AS string) AS observacoes_adicionais,
CAST(last_edite AS datetime) AS ultima_edicao,
geometry
FROM `rj-escritorio-dev.dados_mestres_staging.zoneamento_urbano`